namespace: flowerysong
name: hvault
version: 0.2.0

authors:
  - Paul Arthur <paul.arthur@flowerysong.com> (@flowerysong)

tags:
  - hashicorp
  - vault
  - hashi_vault

readme: README.md
license_file: COPYING
description: Plugins for interacting with HashiCorp Vault

repository: https://github.com/flowerysong/ansible-flowerysong.hvault
issues: https://github.com/flowerysong/ansible-flowerysong.hvault/issues

build_ignore:
  - update-meta.py
