name: ansible-test
on:
  push:
  pull_request:
  schedule:
    - cron: 48 16 * * *

env:
  COLL_NS: flowerysong
  COLL_NAME: hvault
  PYTHON_VERSION: 3.8
  ANSIBLE_COLLECTIONS_PATHS: ${{ github.workspace }}

jobs:
  build_collection:
    name: build collection
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'ansible-core>2.11<2.12'

      - name: Build collection
        run: ansible-galaxy collection build -vv

      - name: Install collection
        run: ansible-galaxy collection install ${{ env.COLL_NS }}-${{ env.COLL_NAME }}-*.tar.gz

      - name: Make sure metadata is up to date
        run: |
          ./update-meta.py
          git diff
          git status --porcelain | grep -q '^ M' && exit 1 || exit 0

      - name: Upload collection
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.COLL_NS }}-${{ env.COLL_NAME }}-*.tar.gz
          name: ${{ env.COLL_NS }}-${{ env.COLL_NAME }}

  static_analysis:
    needs: build_collection
    name: static analysis (${{ matrix.ansible_version.name }})
    strategy:
      fail-fast: true
      matrix:
        ansible_version:
          - name: ansible-base 2.10
            version: ansible-base>2.10<2.11
          - name: ansible-core 2.11
            version: ansible-core>2.11<2.12
          - name: ansible-core devel
            version: git+https://github.com/ansible/ansible#egg=ansible-core
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install '${{ matrix.ansible_version.version }}' pycodestyle pylint pyyaml voluptuous yamllint junit-xml

      - name: Download collection
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.COLL_NS }}-${{ env.COLL_NAME }}

      - name: Install collection
        run: ansible-galaxy collection install ${{ env.COLL_NS }}-${{ env.COLL_NAME }}-*.tar.gz

      - name: Run tests
        run: ansible-test sanity -v --color --python ${{ env.PYTHON_VERSION }}
        working-directory: ./ansible_collections/${{ env.COLL_NS }}/${{ env.COLL_NAME }}

  integration:
    name: integration (Vault ${{ matrix.vault_version }}, ${{ matrix.ansible_version.name }})
    needs: build_collection
    strategy:
      fail-fast: false
      matrix:
        ansible_version:
          - name: ansible-core 2.11
            version: ansible-core>2.11<2.12
        vault_version:
          - 1.5.7
          - 1.6.3
          - 1.7.0
        include:
          - ansible_version:
              name: ansible-base 2.10
              version: ansible-base>2.10<2.11
            vault_version: 1.7.0
          - ansible_version:
              name: ansible-core devel
              version: git+https://github.com/ansible/ansible#egg=ansible-core
            vault_version: 1.7.0
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install '${{ matrix.ansible_version.version }}' pyyaml junit-xml

      - name: Download collection
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.COLL_NS }}-${{ env.COLL_NAME }}

      - name: Install collection
        run: ansible-galaxy collection install ${{ env.COLL_NS }}-${{ env.COLL_NAME }}-*.tar.gz

      - name: Set Vault version
        run: "echo 'vault_version: ${{ matrix.vault_version }}' > tests/integration/integration_config.yml"
        working-directory: ./ansible_collections/${{ env.COLL_NS }}/${{ env.COLL_NAME }}

      - name: Run integration tests
        run: ansible-test integration -vvv --color
        working-directory: ./ansible_collections/${{ env.COLL_NS }}/${{ env.COLL_NAME }}
